name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 3:21
    - cron: '21 3 * * *'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: pre-commit/action@v3.0.0

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version:
          - name: pypy-3.8
            toxenv: pypy3-tests
          - name: pypy-3.8
            toxenv: pypypytest3
          - name: 3.7
            toxenv: py37-build
          - name: 3.7
            toxenv: py37-tests
          - name: 3.8
            toxenv: py38-build
          - name: 3.8
            toxenv: py38-tests
          - name: 3.9
            toxenv: py39-build
          - name: 3.9
            toxenv: py39-tests
          - name: "3.10"
            toxenv: py310-build
          - name: "3.10"
            toxenv: py310-tests
          - name: "3.10"
            toxenv: docs-dirhtml
          - name: "3.10"
            toxenv: docs-doctest
          - name: "3.10"
            toxenv: docs-linkcheck
          - name: "3.10"
            toxenv: docs-spelling
          - name: "3.10"
            toxenv: docs-style
          - name: "3.10"
            toxenv: readme
          - name: "3.10"
            toxenv: safety
          - name: "3.10"
            toxenv: secrets
          - name: "3.10"
            toxenv: style

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version.name }}
    - name: Install dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install -y libenchant-dev
      if: runner.os == 'Linux' && startsWith(matrix.python-version.toxenv, 'docs-')
    - name: Install dependencies
      run: brew install enchant
      if: runner.os == 'macOS' && startsWith(matrix.python-version.toxenv, 'docs-')
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox -e "${{ matrix.python-version.toxenv }}"

  packaging:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python -m pip install build
    - name: Create packages
      run: python -m build .
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
    - name: Create Release Notes
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.request(`POST /repos/${{ github.repository }}/releases`, {
            tag_name: "${{ github.ref }}",
            generate_release_notes: true
          });
